### PR TITLE
GZIP support

### PR DESCRIPTION
**Pull request by Arvi3d**
Recognize GZIPed style files and decompress it

### CODE REVIEW

**Comment by Arvi3d** [comment]
Please merge this pull request asap. Your app is awesome. I'd like to use official release from PYPI, not github repo

**Comment by dlanger** [comment]
Interesting idea, I'll take a look this evening when I get home.

**Comment by Arvi3d** [comment]
Ok, let me know, if there are some issues.
It works for me pretty well.
I already put it to production.

**Comment by dlanger** [comment]
@Arvi3d I'm not going to merge this one, as I (think I) solved the same problem by replacing `urllib` with with `requests`, which I'd been meaning to do for a while (and which does `gzip` [out of the box](http://docs.python-requests.org/en/latest/community/faq/#encoded-data)).

I've pushed a new version to PyPI - if that doesn't work for you, we can re-evaluate why and I'll push another one.

**Comment by Arvi3d** [comment]
Thank you very much for your effort. I’ll check it.

**Comment by Arvi3d** [comment]
yes, it works. thanks.

**Pull request closed without merging**
