### PR TITLE
don't verify SSL certificates of css files

### PR DESCRIPTION
**Pull request by Arvi3d**
Amazone CDN: CloudFront fails.
To reproduce the problem try this:
>>> import requests
>>> requests.get('https://d2fd5orah3cbsb.cloudfront.net/CACHE/css/86199a1a6687.css')
...
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>> requests.get('https://d2fd5orah3cbsb.cloudfront.net/CACHE/css/86199a1a6687.css', verify=False)
<Response [200]>

Please merge it and make a new release on PYPI. Thank you for your effort. This lib is great.

### CODE REVIEW

**Comment by dlanger** [comment]
I'm inclined not to accept this patch, as I think that if someone chooses to serve their CSS over SSL/TLS, we should respect their wishes and make full use of what SSL/TLS offers. Since you provided a nice reproduction case, though, I'll try it on my machines.

On Windows 10 w/ Anaconda I get a warning, but it still works:
```
In [1]: import requests

In [2]: requests.get('https://d2fd5orah3cbsb.cloudfront.net/CACHE/css/86199a1a6687.css')
C:\Users\Dan\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Out[2]: <Response [200]>
```

On Ubuntu 15.04, it works fine:
```
In [1]: import requests

In [2]: requests.get('https://d2fd5orah3cbsb.cloudfront.net/CACHE/css/86199a1a6687.css')
Out[2]: <Response [200]>
```

Given the above, I think the problem is somehow related to the root certificates you have installed on the machine you're running this one. The certificate for that URL is the top-level wildcard `*.cloudfront.net` (which I use elsewhere with no problems).

I would try making sure your system time and date is correct (you could have a date/time set to when he certificate is no longer valid), doing a certificate update in the way that makes sense for your OS, and going through some of the suggestions [here](https://www.google.ca/search?q=routines%3ASSL3_GET_SERVER_CERTIFICATE%3Acertificate+verify+failed&rlz=1C1CHFX_enCA638CA639&oq=routines%3ASSL3_GET_SERVER_CERTIFICATE%3Acertificate+verify+failed&aqs=chrome..69i57j69i58j69i60&sourceid=chrome&es_sm=93&ie=UTF-8) - the problem you're having is that `requests` can't find a valid root certificate to use with CloudFront.

**Comment by Arvi3d** [comment]
thank you for quick reply. I’ll double check.

**Comment by dlanger** [comment]
If you can `curl` the URL fine from that machine, try setting the `REQUESTS_CA_BUNDLE ` environment variable to whatever certificate chain OpenSSL uses (which could be `/etc/ssl/certs/ca-certificates.crt`, but might be something else)

**Comment by Arvi3d** [comment]
Hi Daniel,

It helps with other sites, youtube for example.
But not with Amazone Cloudfront. I gave up and turned off that verification. Anyway it’s just a stylesheet.

**Pull request closed without merging**
